"""
Stage 7 fault configuration for the Rotax 915-series simulator.

PROVENANCE RULE
---------------
Numbers marked "documented" come from the project's Rotax fault library /
documented operating limits. Severity multipliers marked "assumption" are
simulation design choices and are NOT Rotax specifications.

Stage 5 remains frozen. Stage 7 operates as a separate abnormal-state layer.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final


# ---------------------------------------------------------------------------
# Documented Rotax limits / criteria used for labeling and validation.
# ---------------------------------------------------------------------------

MAX_COOLANT_TEMP_C: Final[float] = 120.0
MAX_OIL_TEMP_C: Final[float] = 130.0
MAX_EGT_C: Final[float] = 950.0

EGT_SPLIT_LIMIT_HIGH_FUELFLOW_C: Final[float] = 200.0
EGT_SPLIT_LIMIT_LOW_FUELFLOW_C: Final[float] = 500.0

FUEL_PRESSURE_NORMAL_MIN_BAR: Final[float] = 2.9
FUEL_PRESSURE_NORMAL_MAX_BAR: Final[float] = 3.2

FUEL_PRESSURE_TRANSIENT_MIN_BAR: Final[float] = 2.5
FUEL_PRESSURE_TRANSIENT_MAX_BAR: Final[float] = 3.5
FUEL_PRESSURE_TRANSIENT_MAX_DURATION_S: Final[float] = 3.0

OIL_PRESSURE_HIGH_RPM_MIN_BAR: Final[float] = 2.0
OIL_PRESSURE_HIGH_RPM_MAX_BAR: Final[float] = 5.0
OIL_PRESSURE_LOW_RPM_MIN_BAR: Final[float] = 0.8

# ---------------------------------------------------------------------------
# Stage 7 simulation assumptions.
# These are intentionally NOT described as manufacturer specifications.
# ---------------------------------------------------------------------------

FAULT_SEVERITIES: Final[dict[str, float]] = {
    "mild": 1.0 / 3.0,
    "moderate": 2.0 / 3.0,
    "severe": 1.0,
}

# Fault effect endpoints. These are normalized Stage-7 assumptions.
# The physical output is derived from the existing Stage-4 telemetry model.
MISFIRE_COMBUSTION_EFFECT: Final[dict[str, float]] = {
    "mild": 0.10,
    "moderate": 0.25,
    "severe": 0.45,
}

COOLING_EFFECTIVENESS_LOSS: Final[dict[str, float]] = {
    "mild": 0.10,
    "moderate": 0.20,
    "severe": 0.30,
}

LUBRICATION_FLOW_LOSS: Final[dict[str, float]] = {
    "mild": 0.10,
    "moderate": 0.25,
    "severe": 0.40,
}

SENSOR_DRIFT_FRACTION: Final[dict[str, float]] = {
    "mild": 0.02,
    "moderate": 0.05,
    "severe": 0.10,
}

FUEL_PRESSURE_FAULT_LOW_BAR: Final[dict[str, float]] = {
    "mild": 2.75,
    "moderate": 2.55,
    "severe": 2.30,
}

# Faults actually generated by the first Stage-7 implementation.
ACTIVE_FAULTS: Final[tuple[str, ...]] = (
    "misfire",
    "cooling_degradation",
    "lubrication_degradation",
    "sensor_drift",
    "fuel_pressure_deviation",
)


@dataclass(frozen=True)
class FaultDefinition:
    fault_type: str
    category: str
    injection_layer: str
    documented_basis: str
    assumption_basis: str


FAULT_DEFINITIONS: Final[dict[str, FaultDefinition]] = {
    "misfire": FaultDefinition(
        "misfire",
        "physical_proxy",
        "stage7_health_layer",
        "EGT spread criteria: 200 C above 3 L/h fuel flow, 500 C below 3 L/h.",
        "Cylinder-specific combustion-effect proxy; severity controls the maximum reduction.",
    ),
    "cooling_degradation": FaultDefinition(
        "cooling_degradation",
        "physical_proxy",
        "stage7_health_layer",
        "Coolant operating maximum: 120 C; oil operating maximum: 130 C.",
        "Cooling-effectiveness loss of 10/20/30 percent for mild/moderate/severe.",
    ),
    "lubrication_degradation": FaultDefinition(
        "lubrication_degradation",
        "physical_proxy",
        "stage7_health_layer",
        "Oil pressure envelope: 2-5 bar above 3500 RPM; minimum 0.8 bar below 3500 RPM.",
        "Effective lubrication-flow loss of 10/25/40 percent.",
    ),
    "sensor_drift": FaultDefinition(
        "sensor_drift",
        "sensor",
        "measurement_layer",
        "Sensor-fault category is supported by the project's fault research.",
        "Single-channel gradual drift of 2/5/10 percent.",
    ),
    "fuel_pressure_deviation": FaultDefinition(
        "fuel_pressure_deviation",
        "fuel_system_proxy",
        "stage7_health_layer",
        "Normal fuel pressure: 2.9-3.2 bar; 2.5-3.5 bar transient allowance for <=3 s after power-setting change.",
        "Healthy baseline modeled at 3.0 bar; fault pulls pressure below normal range.",
    ),
}


LIMIT_DEFINITIONS: Final[dict[str, tuple[str, float | None, float | None]]] = {
    "coolant_temp_C": ("coolant_overtemperature", None, MAX_COOLANT_TEMP_C),
    "oil_temperature_C": ("oil_overtemperature", None, MAX_OIL_TEMP_C),
    "EGT_max_C": ("egt_overtemperature", None, MAX_EGT_C),
    "fuel_pressure_bar": (
        "fuel_pressure_out_of_normal_range",
        FUEL_PRESSURE_NORMAL_MIN_BAR,
        FUEL_PRESSURE_NORMAL_MAX_BAR,
    ),
}


MODEL_VERSION: Final[str] = "stage7_fault_layer_v1"
